#!/bin/bash

set -e

PREFIX="/usr/share/gpioctrl"
ROOT=${CHECKOUT:-${PREFIX}}

. "${ROOT}"/functions

# gpio pinmap
# +-----+-----+---------+------+---+----------+---+------+---------+-----+-----+
# | I/O | wPi |   Name  | Mode | V | Physical | V | Mode |  Name   | wPi | I/O |
# +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
# |     |     |    3.3V |      |   |  1 || 2  |   |      | 5V      |     |     |
# | ??? |   8 |    SDA0 |   IN | 1 |  3 || 4  |   |      | 5V      |     |     |
# | ??? |   9 |    SCL0 |   IN | 1 |  5 || 6  |   |      | 0V      |     |     |
# | ??? |   7 |      IO |   IN | 1 |  7 || 8  | 0 | IN   | UART.TX | 15  | ??? |
# |     |     |      0V |      |   |  9 || 10 | 0 | IN   | UART.RX | 16  | ??? |
# | ??? |   0 |      IO |   IN | 0 | 11 || 12 | 0 | IN   | IO      | 1   | ??? |
# | ??? |   2 |      IO |   IN | 0 | 13 || 14 |   |      | 0V      |     |     |
# | ??? |   3 |      IO |   IN | 0 | 15 || 16 | 0 | IN   | IO      | 4   | ??? |
# |     |     |    3.3V |      |   | 17 || 18 | 0 | IN   | IO      | 5   | ??? |
# | ??? |  12 | SPI.TXD |   IN | 0 | 19 || 20 |   |      | 0V      |     |     |
# | ??? |  13 | SPI.RXD |   IN | 0 | 21 || 22 | 0 | IN   | IO      | 6   | ??? |
# | ??? |  14 | SPI.CLK |   IN | 0 | 23 || 24 | 0 | IN   | SPI.CS0 | 10  | ??? |
# |     |     |      0V |      |   | 25 || 26 | 0 | IN   | IO      | 11  | ??? |
# | ??? |  30 |    SDA1 |   IN | 1 | 27 || 28 | 1 | IN   | SCL1    | 31  | ??? |
# | ??? |  21 |      IO |   IN | 0 | 29 || 30 |   |      | 0V      |     |     |
# | ??? |  22 |      IO |   IN | 0 | 31 || 32 | 0 | IN   | IO      | 26  | ??? |
# | ??? |  23 |      IO |   IN | 1 | 33 || 34 |   |      | 0V      |     |     |
# | ??? |  24 |      IO |   IN | 0 | 35 || 36 | 0 | IN   | IO      | 27  | ??? |
# |     |  25 |    AIN1 |      |   | 37 || 38 |   |      | 1V8     | 28  |     |
# |     |     |      0V |      |   | 39 || 40 |   |      | AIN0    | 29  |     |
# +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
# | I/O | wPi |   Name  | Mode | V | Physical | V | Mode |  Name   | wPi | I/O |
# +-----+-----+---------+------+---+----------+---+------+---------+-----+-----+

options=$(getopt -o a:gh -l alt:,gpio,help -- "$@")
eval set -- "${options}"

while true; do
  case "$1" in
    -a|--alt) shift
      ALT="$1"
      case "${ALT}" in
        can)
          . "${ROOT}"/can_ctrl
          exit 0
          ;;
        i2c)
          . "${ROOT}"/i2c_ctrl
          exit 0
          ;;
        spi)
          . "${ROOT}"/spi_ctrl
          exit 0
          ;;
        *)
          echo "Not support \"${ALT}\""
          ;;
      esac
      ;;
    -g|--gpio)
      . "${ROOT}"/gpio_ctrl
      exit 0
      ;;
    -h|--help)
      Usage
      ;;
    --) shift
      break
      ;;
    *)
      echo "Not implemeted: $1" >&2
      ;;
  esac
  shift
done

# vim: set ft=sh ts=2 sw=2 sts=2 et
